### ISSUE TITLE
Error while trying to bring up first instance

### ISSUE THREAD

**Issue by StephenHoffmann** [blueboxgroup/razor-vagrant-lab#2]
Installation worked but I am getting:

[root@ph1226401]~/downloads/razor-vagrant-lab# /opt/vagrant/bin/vagrant up razor
/opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- berkshelf/vagrant (LoadError)
        from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /local/home/shoffmann/downloads/razor-vagrant-lab/Vagrantfile:5:in `<top (required)>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:115:in`load'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:115:in `block in procs_for_source'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config.rb:41:in`block in capture_configures'
        from internal:prelude:10:in `synchronize'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config.rb:36:in`capture_configures'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:114:in `procs_for_source'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:51:in`block in set'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:45:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config/loader.rb:45:in`set'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/environment.rb:377:in `block in load_config!'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/environment.rb:392:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/environment.rb:392:in `load_config!'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/environment.rb:327:in`load!'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.0.6/bin/vagrant:40:in `<top (required)>'
        from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in`load'
        from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'

**Comment by ChrisLundquist** [comment]
@StephenHoffmann do you have the berkshelf gem installed? It looks like you might be using the vagrant binary package installer in which case I think you'll need to run

`vagrant gem install berkshelf`

**Comment by StephenHoffmann** [comment]
@ChrisLundquist Thanks for getting back to me! I installed via cloning the project and using the bootstrap script. When I do a 'vagrant gem install berkshelf', I get the exact same error  so I tried 'gem install berkshelf' and after installing successfully, I still get the same error trying to use the vagrant binary in any way. 

Could I be missing a package? I found a thread here that has the same issue: https://github.com/RiotGames/berkshelf/issues/368

And removing the berkshelf line from the Vagrantfile allowed me to bring up razor/puppet without any issues.

**Comment by ChrisLundquist** [comment]
We have been using the vagrant gem, despite the looming deprecation warnings. This is a good use case to explore on how to use Berkshelf + Vagrant binary.

**Comment by StephenHoffmann** [comment]
Strangely, I attempted installing the vagrant gem and didn't get anywhere. (It gave the same error.) Right now, I'm just a little worried about commenting out that require 'berkshelf/vagrant' line. Is this possibly going to cause problems?

**Comment by mhenke** [comment]
vagrant gem install berkshelf gave me this error 

/opt/vagrant/embedded/gems/gems/vagrant-1.0.6/lib/vagrant/config/top.rb:29:in `method_missing': undefined method`vbguest' for #Vagrant::Config::Top:0x00000001734ff0

**Comment by pouicr** [comment]
Same error on "vagrant up" using v1.0.7.

Interesting to know how you solved it.

thx

**Comment by itsNikolay** [comment]
Same error 

```
itsnikolay@itsnikolay:~/Vagrant/test$ vagrant
/home/itsnikolay/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- vagrant (LoadError)
    from /home/itsnikolay/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/bin/vagrant:3:in `<main>'
```
